package com.pjj.xsp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pjj.xsp.db.DateTask;
import com.pjj.xsp.db.OrderTask;

import com.pjj.xsp.db.DateTaskDao;
import com.pjj.xsp.db.OrderTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dateTaskDaoConfig;
    private final DaoConfig orderTaskDaoConfig;

    private final DateTaskDao dateTaskDao;
    private final OrderTaskDao orderTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dateTaskDaoConfig = daoConfigMap.get(DateTaskDao.class).clone();
        dateTaskDaoConfig.initIdentityScope(type);

        orderTaskDaoConfig = daoConfigMap.get(OrderTaskDao.class).clone();
        orderTaskDaoConfig.initIdentityScope(type);

        dateTaskDao = new DateTaskDao(dateTaskDaoConfig, this);
        orderTaskDao = new OrderTaskDao(orderTaskDaoConfig, this);

        registerDao(DateTask.class, dateTaskDao);
        registerDao(OrderTask.class, orderTaskDao);
    }
    
    public void clear() {
        dateTaskDaoConfig.clearIdentityScope();
        orderTaskDaoConfig.clearIdentityScope();
    }

    public DateTaskDao getDateTaskDao() {
        return dateTaskDao;
    }

    public OrderTaskDao getOrderTaskDao() {
        return orderTaskDao;
    }

}
