package com.pjj.xsp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATE_TASK".
*/
public class DateTaskDao extends AbstractDao<DateTask, Long> {

    public static final String TABLENAME = "DATE_TASK";

    /**
     * Properties of entity DateTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_date = new Property(0, Long.class, "id_date", true, "_id");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property Hour = new Property(2, String.class, "hour", false, "HOUR");
        public final static Property OrderId = new Property(3, String.class, "orderId", false, "ORDER_ID");
    }


    public DateTaskDao(DaoConfig config) {
        super(config);
    }
    
    public DateTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATE_TASK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id_date
                "\"DATE\" TEXT NOT NULL ," + // 1: date
                "\"HOUR\" TEXT NOT NULL ," + // 2: hour
                "\"ORDER_ID\" TEXT NOT NULL );"); // 3: orderId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATE_TASK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DateTask entity) {
        stmt.clearBindings();
 
        Long id_date = entity.getId_date();
        if (id_date != null) {
            stmt.bindLong(1, id_date);
        }
        stmt.bindString(2, entity.getDate());
        stmt.bindString(3, entity.getHour());
        stmt.bindString(4, entity.getOrderId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DateTask entity) {
        stmt.clearBindings();
 
        Long id_date = entity.getId_date();
        if (id_date != null) {
            stmt.bindLong(1, id_date);
        }
        stmt.bindString(2, entity.getDate());
        stmt.bindString(3, entity.getHour());
        stmt.bindString(4, entity.getOrderId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DateTask readEntity(Cursor cursor, int offset) {
        DateTask entity = new DateTask( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id_date
            cursor.getString(offset + 1), // date
            cursor.getString(offset + 2), // hour
            cursor.getString(offset + 3) // orderId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DateTask entity, int offset) {
        entity.setId_date(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.getString(offset + 1));
        entity.setHour(cursor.getString(offset + 2));
        entity.setOrderId(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DateTask entity, long rowId) {
        entity.setId_date(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DateTask entity) {
        if(entity != null) {
            return entity.getId_date();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DateTask entity) {
        return entity.getId_date() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
