package com.pjj.xsp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER_TASK".
*/
public class OrderTaskDao extends AbstractDao<OrderTask, Long> {

    public static final String TABLENAME = "ORDER_TASK";

    /**
     * Properties of entity OrderTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderId = new Property(1, String.class, "orderId", false, "ORDER_ID");
        public final static Property PeopleInfo = new Property(2, String.class, "peopleInfo", false, "PEOPLE_INFO");
        public final static Property DiyInfo = new Property(3, String.class, "diyInfo", false, "DIY_INFO");
    }


    public OrderTaskDao(DaoConfig config) {
        super(config);
    }
    
    public OrderTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER_TASK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ORDER_ID\" TEXT NOT NULL ," + // 1: orderId
                "\"PEOPLE_INFO\" TEXT," + // 2: peopleInfo
                "\"DIY_INFO\" TEXT);"); // 3: diyInfo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER_TASK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrderTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getOrderId());
 
        String peopleInfo = entity.getPeopleInfo();
        if (peopleInfo != null) {
            stmt.bindString(3, peopleInfo);
        }
 
        String diyInfo = entity.getDiyInfo();
        if (diyInfo != null) {
            stmt.bindString(4, diyInfo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrderTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getOrderId());
 
        String peopleInfo = entity.getPeopleInfo();
        if (peopleInfo != null) {
            stmt.bindString(3, peopleInfo);
        }
 
        String diyInfo = entity.getDiyInfo();
        if (diyInfo != null) {
            stmt.bindString(4, diyInfo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OrderTask readEntity(Cursor cursor, int offset) {
        OrderTask entity = new OrderTask( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // orderId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // peopleInfo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // diyInfo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrderTask entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderId(cursor.getString(offset + 1));
        entity.setPeopleInfo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDiyInfo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OrderTask entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OrderTask entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OrderTask entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
