package com.pjj.xsp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MINE_PLAY_TASK".
*/
public class MinePlayTaskDao extends AbstractDao<MinePlayTask, Long> {

    public static final String TABLENAME = "MINE_PLAY_TASK";

    /**
     * Properties of entity MinePlayTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderId = new Property(1, String.class, "orderId", false, "ORDER_ID");
        public final static Property TemplateType = new Property(2, String.class, "templateType", false, "TEMPLATE_TYPE");
        public final static Property ShowTime = new Property(3, int.class, "showTime", false, "SHOW_TIME");
        public final static Property Json = new Property(4, String.class, "json", false, "JSON");
    }


    public MinePlayTaskDao(DaoConfig config) {
        super(config);
    }
    
    public MinePlayTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MINE_PLAY_TASK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ORDER_ID\" TEXT NOT NULL ," + // 1: orderId
                "\"TEMPLATE_TYPE\" TEXT," + // 2: templateType
                "\"SHOW_TIME\" INTEGER NOT NULL ," + // 3: showTime
                "\"JSON\" TEXT NOT NULL );"); // 4: json
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MINE_PLAY_TASK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MinePlayTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getOrderId());
 
        String templateType = entity.getTemplateType();
        if (templateType != null) {
            stmt.bindString(3, templateType);
        }
        stmt.bindLong(4, entity.getShowTime());
        stmt.bindString(5, entity.getJson());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MinePlayTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getOrderId());
 
        String templateType = entity.getTemplateType();
        if (templateType != null) {
            stmt.bindString(3, templateType);
        }
        stmt.bindLong(4, entity.getShowTime());
        stmt.bindString(5, entity.getJson());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MinePlayTask readEntity(Cursor cursor, int offset) {
        MinePlayTask entity = new MinePlayTask( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // orderId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // templateType
            cursor.getInt(offset + 3), // showTime
            cursor.getString(offset + 4) // json
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MinePlayTask entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderId(cursor.getString(offset + 1));
        entity.setTemplateType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setShowTime(cursor.getInt(offset + 3));
        entity.setJson(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MinePlayTask entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MinePlayTask entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MinePlayTask entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
